package imagejai.engine.security;

import imagejai.config.Constants;
import imagejai.config.PrivacyPosture;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Clock;
import java.time.Instant;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 * Generates the printable Data Governance statement under AI_Exports as a
 * self-contained HTML page; a browser's Print command turns it into a PDF.
 */
public final class DataHandlingStatementGenerator {
    private static final String REPO_URL = "github.com/Jay2owe/ImageJAI";
    private static final String STYLE =
            "@page{size:A4;margin:16mm}"
            + "body{font:10pt/1.45 Arial,'Segoe UI',sans-serif;color:#000;"
            + "max-width:180mm;margin:24px auto;padding:0 16px}"
            + "h1{font-size:15pt;margin:0 0 6px}"
            + "h2{font-size:10.5pt;margin:14px 0 4px;break-after:avoid}"
            + "p{margin:2px 0}ul{margin:2px 0;padding-left:18px}"
            + "hr{border:0;border-top:1px solid #bebec3;margin:8px 0}"
            + ".indent{margin-left:14px}.vendor{font-weight:bold;margin-top:6px}"
            + "footer{margin-top:16px;font-size:9pt;color:#444}";

    private final Path projectFolder;
    private final PrivacyPosture posture;
    private final Clock clock;
    private final String version;

    public DataHandlingStatementGenerator(Path projectFolder, PrivacyPosture posture) {
        this(projectFolder, posture, Clock.systemDefaultZone(), Constants.VERSION);
    }

    DataHandlingStatementGenerator(Path projectFolder, PrivacyPosture posture,
                                   Clock clock, String version) {
        if (projectFolder == null) {
            throw new IllegalArgumentException("projectFolder is required");
        }
        this.projectFolder = projectFolder.toAbsolutePath().normalize();
        this.posture = posture == null ? PrivacyPosture.defaultPosture() : posture;
        this.clock = clock == null ? Clock.systemDefaultZone() : clock;
        this.version = version == null || version.trim().isEmpty()
                ? Constants.VERSION
                : version.trim();
    }

    public Path generate() throws IOException {
        LocalDate generatedDate = LocalDate.now(clock);
        Path outDir = projectFolder.resolve("AI_Exports");
        Files.createDirectories(outDir);
        Path out = outDir.resolve("DataHandlingStatement_" + projectName()
                + "_" + DateTimeFormatter.BASIC_ISO_DATE.format(generatedDate)
                + ".html");

        Html html = new Html();
        html.raw("<!DOCTYPE html>\n<html lang=\"en\"><head><meta charset=\"utf-8\">"
                + "<title>Data Handling Statement — " + escape(projectName())
                + "</title><style>" + STYLE + "</style></head><body>\n");
        writeHeader(html, generatedDate);
        writeSection1Purpose(html);
        writeSection2DataFlow(html);
        writeSection3Pseudonymisation(html);
        writeSection4VendorTerms(html);
        writeSection5AuditSummary(html, AuditLog.summaryFor(projectFolder));
        writeSection6OptOut(html);
        writeSection7Limitations(html);
        html.raw("<footer>Generated by ImageJAI v" + escape(version) + " — "
                + escape(REPO_URL) + "</footer>\n</body></html>\n");
        Files.write(out, html.toString().getBytes(StandardCharsets.UTF_8));
        return out;
    }

    private void writeHeader(Html html, LocalDate generatedDate) {
        html.raw("<h1>ImageJAI — Data Handling Statement</h1>\n");
        html.p("Project: " + projectName());
        html.p("Generated: " + generatedDate + "    Posture in force: " + posture.label());
        html.p("ImageJAI version: " + version);
        html.raw("<hr>\n");
    }

    private void writeSection1Purpose(Html html) {
        html.section("1. Purpose");
        html.p("This statement summarises the data-handling posture of the "
                + "ImageJAI plugin for the named project. Suitable for Research Ethics "
                + "Committee amendments and Data Management Plans.");
    }

    private void writeSection2DataFlow(Html html) {
        html.section("2. Data flow");
        html.list(
                "Images are read from " + projectFolder + " on the local machine.",
                "The user selects files (and series-within-files) via the "
                        + "Browse Files dialog or Fiji's File menu. Identifiable filenames "
                        + "remain on the local machine.",
                "The ImageJAI TCP server (localhost:7746) exposes commands "
                        + "to the selected agent CLI.",
                "Outbound responses pass through the PseudonymisationFilter "
                        + "before reaching the agent process.",
                "The agent CLI communicates with the configured model "
                        + "endpoint (see §4).");
    }

    private void writeSection3Pseudonymisation(Html html) {
        html.section("3. Pseudonymisation scheme (UK GDPR Art. 4(5))");
        html.p("The following are tokenised before leaving the JVM in "
                + "Pseudonymised and On-premises postures:");
        html.list(
                "File and folder paths (whole-file and series-within-file)",
                "OME-XML elements: Experimenter, Description, StageLabel, "
                        + "AcquisitionDate, InstrumentRef, InstrumentSerialNumber, Annotation",
                "Results-table columns: Label, Slice (when non-numeric)",
                "Dialog and window titles",
                "Error and log messages");
        html.p("Image-pixel handling is differentiated by source:");
        html.list(
                "Microscopy image content: downsampled to ≤512×512 and "
                        + "text burn-ins (Incucyte timestamps, scanner labels) masked "
                        + "before transmission.",
                "GUI / dialog / window screenshots: refused and replaced "
                        + "with a hash placeholder.",
                "On-demand visual override: the agent may request "
                        + "full-resolution pixel access for one call; the user must "
                        + "explicitly grant; burn-in mask still applied; the grant and "
                        + "consumption are logged in the audit trail.");
        html.p("The token map is held in JVM memory only and destroyed at session end.");
    }

    private void writeSection4VendorTerms(Html html) {
        html.section("4. Vendor contractual posture");
        for (VendorTermsRegistry.VendorTerm term : VendorTermsRegistry.ALL) {
            html.raw("<p class=\"vendor\">" + escape(term.vendor() + ":") + "</p>\n");
            html.raw("<p class=\"indent\">" + escape(vendorStatement(term)) + "</p>\n");
        }
    }

    private void writeSection5AuditSummary(Html html, AuditSummary summary) {
        AuditSummary s = summary == null
                ? new AuditSummary(null, 0, null, null, 0L, 0L, 0, 0, 0, 0,
                        null, null, null)
                : summary;
        html.section("5. Audit trail");
        html.p("Location: AI_Exports/imagejai_audit.csv");
        html.p("Rows in this project to date: " + s.rowCount());
        html.p("Date range: " + dateRange(s.first(), s.last()));
        html.p("Of which:");
        html.raw("<p class=\"indent\">" + escape("Pseudonymised calls: " + s.pseudonymised())
                + "</p>\n<p class=\"indent\">"
                + escape("Visual override grants: " + s.visualOverrideGrants())
                + "</p>\n<p class=\"indent\">"
                + escape("Posture downshifts: " + s.downshifts()) + "</p>\n");
    }

    private void writeSection6OptOut(Html html) {
        html.section("6. Opt-out and escalation");
        html.p("Set the Privacy Posture to On-premises via the folder "
                + "banner or the launcher Configuration Pane. In this mode the "
                + "agent dropdown is filtered to local-binary agents only, "
                + "*-cloud Ollama tags are refused, and the visual override is "
                + "unavailable.");
    }

    private void writeSection7Limitations(Html html) {
        html.section("7. Limitations");
        html.list(
                "Pseudonymisation remains reversible inside the live JVM "
                        + "session so ImageJAI can resolve tokens back to local files.",
                "The pseudonymisation filter governs TCP responses. For "
                        + "external CLIs (Claude Code in a separate terminal), filenames "
                        + "typed directly into the agent chat are NOT intercepted. The "
                        + "Browse Files dialog and the ImageJAI console's redaction of "
                        + "typed paths mitigate this.",
                "Burn-in text detection uses a fast heuristic catching "
                        + "~90% of cases; configurable per-format masks cover known "
                        + "microscope vendors (Incucyte, Aperio).",
                "This statement is generated automatically from posture "
                        + "and audit metadata at the moment of generation.");
    }

    private String vendorStatement(VendorTermsRegistry.VendorTerm term) {
        String displayUrl = term.displayUrl();
        String statement = term.statement();
        boolean quoted = term.vendor().startsWith("Anthropic")
                || term.vendor().startsWith("OpenAI")
                || term.vendor().equals("Google Gemini API (paid)");
        String body = quoted ? "\"" + statement + "\"" : statement;
        return displayUrl.isEmpty() ? body : body + " — " + displayUrl;
    }

    private String projectName() {
        Path name = projectFolder.getFileName();
        String raw = name == null ? "project" : name.toString();
        String cleaned = raw.replaceAll("[\\\\/:*?\"<>|]+", "_").trim();
        return cleaned.isEmpty() ? "project" : cleaned;
    }

    private static String dateRange(Instant first, Instant last) {
        if (first == null || last == null) {
            return "none";
        }
        if (first.equals(last)) {
            return first.toString();
        }
        return first + " — " + last;
    }

    static String escape(String text) {
        String value = text == null ? "" : text;
        StringBuilder out = new StringBuilder(value.length() + 16);
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            switch (c) {
                case '&': out.append("&amp;"); break;
                case '<': out.append("&lt;"); break;
                case '>': out.append("&gt;"); break;
                case '"': out.append("&quot;"); break;
                case '\'': out.append("&#39;"); break;
                default: out.append(c);
            }
        }
        return out.toString();
    }

    private static final class Html {
        private final StringBuilder out = new StringBuilder(8192);

        void raw(String markup) { out.append(markup); }

        void section(String title) { out.append("<h2>").append(escape(title)).append("</h2>\n"); }

        void p(String text) { out.append("<p>").append(escape(text)).append("</p>\n"); }

        void list(String... items) {
            out.append("<ul>\n");
            for (String item : items) {
                out.append("<li>").append(escape(item)).append("</li>\n");
            }
            out.append("</ul>\n");
        }

        @Override public String toString() { return out.toString(); }
    }
}
