package imagejai.engine;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Multi-step pipeline orchestration engine.
 * Parses pipeline blocks from LLM responses, executes steps sequentially,
 * and supports resume/retry, export, and batch wrapping.
 */
public class PipelineBuilder {

    private static final Pattern PIPELINE_PATTERN =
            Pattern.compile("<pipeline>(.*?)</pipeline>", Pattern.DOTALL);

    private static final Pattern STEP_PATTERN =
            Pattern.compile("<step\\s+description=\"([^\"]*?)\">(.*?)</step>", Pattern.DOTALL);

    private final CommandEngine commandEngine;

    public PipelineBuilder(CommandEngine commandEngine) {
        this.commandEngine = commandEngine;
    }

    /**
     * A single step in a pipeline.
     */
    public static class PipelineStep {
        public int index;
        public String description;
        public String macroCode;
        public String status;
        public ExecutionResult result;
        public long executionTimeMs;

        public PipelineStep(int index, String description, String macroCode) {
            this.index = index;
            this.description = description;
            this.macroCode = macroCode;
            this.status = "pending";
            this.result = null;
            this.executionTimeMs = 0;
        }
    }

    /**
     * A complete pipeline of ordered steps.
     */
    public static class Pipeline {
        public String name;
        public List<PipelineStep> steps;
        public String status;
        public int currentStepIndex;

        public Pipeline(String name, List<PipelineStep> steps) {
            this.name = name;
            this.steps = steps;
            this.status = "pending";
            this.currentStepIndex = 0;
        }

        /**
         * Export the entire pipeline as a single runnable .ijm macro string.
         */
        public String exportAsMacro() {
            StringBuilder sb = new StringBuilder();
            sb.append("// Pipeline: ").append(name).append("\n");
            sb.append("// Generated by ImageJ AI Assistant\n");
            sb.append("// Steps: ").append(steps.size()).append("\n\n");
            for (int i = 0; i < steps.size(); i++) {
                PipelineStep step = steps.get(i);
                sb.append("// Step ").append(step.index).append(": ").append(step.description).append("\n");
                sb.append(step.macroCode.trim()).append("\n\n");
            }
            return sb.toString();
        }

        /**
         * Get a formatted plain-text status summary.
         */
        public String getStatusSummary() {
            StringBuilder sb = new StringBuilder();
            sb.append("Pipeline: ").append(name).append(" [").append(status).append("]\n");
            for (int i = 0; i < steps.size(); i++) {
                PipelineStep step = steps.get(i);
                String icon;
                if ("success".equals(step.status)) {
                    icon = "[OK]";
                } else if ("running".equals(step.status)) {
                    icon = "[>>]";
                } else if ("failed".equals(step.status)) {
                    icon = "[FAIL]";
                } else if ("skipped".equals(step.status)) {
                    icon = "[SKIP]";
                } else {
                    icon = "[  ]";
                }
                sb.append("  ").append(icon).append(" Step ").append(step.index)
                        .append(": ").append(step.description);
                if (step.executionTimeMs > 0) {
                    sb.append(" (").append(step.executionTimeMs).append("ms)");
                }
                sb.append("\n");
            }
            return sb.toString();
        }
    }

    /**
     * Callback interface for pipeline execution progress.
     */
    public interface PipelineCallback {
        void onStepStarted(PipelineStep step);
        void onStepCompleted(PipelineStep step);
        void onStepFailed(PipelineStep step, String error);
        void onPipelineCompleted(Pipeline pipeline);
        void onPipelineFailed(Pipeline pipeline, PipelineStep failedStep);
    }

    /**
     * Parse a pipeline from an LLM response containing a {@code <pipeline>} block.
     * Extracts step descriptions and macro code from {@code <step>} elements.
     *
     * @param llmResponse the raw LLM response text
     * @return parsed Pipeline, or null if no pipeline block found
     */
    public Pipeline parsePipeline(String llmResponse) {
        if (llmResponse == null || llmResponse.isEmpty()) {
            return null;
        }

        Matcher pipelineMatcher = PIPELINE_PATTERN.matcher(llmResponse);
        if (!pipelineMatcher.find()) {
            return null;
        }

        String pipelineContent = pipelineMatcher.group(1);
        List<PipelineStep> steps = new ArrayList<PipelineStep>();

        Matcher stepMatcher = STEP_PATTERN.matcher(pipelineContent);
        int index = 1;
        while (stepMatcher.find()) {
            String description = stepMatcher.group(1).trim();
            String macroCode = stepMatcher.group(2).trim();
            if (!macroCode.isEmpty()) {
                steps.add(new PipelineStep(index, description, macroCode));
                index++;
            }
        }

        if (steps.isEmpty()) {
            return null;
        }

        // Derive pipeline name from the first step or a generic name
        String name = derivePipelineName(steps);
        return new Pipeline(name, steps);
    }

    /**
     * Execute a pipeline step by step from the beginning.
     * Calls the callback after each step for progress updates.
     * Stops on first failure.
     *
     * @param pipeline the pipeline to execute
     * @param callback progress callback (may be null)
     */
    public void executePipeline(Pipeline pipeline, PipelineCallback callback) {
        pipeline.status = "running";
        pipeline.currentStepIndex = 0;
        executeFromStep(pipeline, 0, callback);
    }

    /**
     * Resume a failed pipeline from the failed step.
     *
     * @param pipeline the pipeline to resume
     * @param callback progress callback (may be null)
     */
    public void resumePipeline(Pipeline pipeline, PipelineCallback callback) {
        // Find the first non-success step
        int resumeFrom = 0;
        for (int i = 0; i < pipeline.steps.size(); i++) {
            PipelineStep step = pipeline.steps.get(i);
            if (!"success".equals(step.status)) {
                resumeFrom = i;
                break;
            }
        }
        pipeline.status = "running";
        executeFromStep(pipeline, resumeFrom, callback);
    }

    /**
     * Retry a specific failed step with modified macro code, then continue.
     *
     * @param pipeline     the pipeline
     * @param stepIndex    0-based index of the step to retry
     * @param newMacroCode replacement macro code for the step
     * @param callback     progress callback (may be null)
     */
    public void retryStep(Pipeline pipeline, int stepIndex, String newMacroCode, PipelineCallback callback) {
        if (stepIndex < 0 || stepIndex >= pipeline.steps.size()) {
            return;
        }
        PipelineStep step = pipeline.steps.get(stepIndex);
        step.macroCode = newMacroCode;
        step.status = "pending";
        step.result = null;
        step.executionTimeMs = 0;
        pipeline.status = "running";
        executeFromStep(pipeline, stepIndex, callback);
    }

    /**
     * Save a pipeline as a .ijm macro file.
     *
     * @param pipeline the pipeline to save
     * @param filePath the file path to write to
     */
    public void savePipeline(Pipeline pipeline, String filePath) {
        String macroContent = pipeline.exportAsMacro();
        FileWriter writer = null;
        try {
            writer = new FileWriter(new File(filePath));
            writer.write(macroContent);
        } catch (IOException e) {
            System.err.println("[ImageJAI] Failed to save pipeline: " + e.getMessage());
        } finally {
            if (writer != null) {
                try {
                    writer.close();
                } catch (IOException ignored) {
                    // ignore
                }
            }
        }
    }

    /**
     * Create a batch wrapper macro that runs the pipeline on all images in a folder.
     *
     * @param pipeline     the pipeline
     * @param inputFolder  path to the input folder
     * @param outputFolder path to the output folder
     * @return the batch macro code string
     */
    public String createBatchMacro(Pipeline pipeline, String inputFolder, String outputFolder) {
        StringBuilder sb = new StringBuilder();
        sb.append("// Batch Pipeline: ").append(pipeline.name).append("\n");
        sb.append("// Generated by ImageJ AI Assistant\n\n");
        sb.append("inputDir = \"").append(escapeForMacro(inputFolder)).append("\";\n");
        sb.append("outputDir = \"").append(escapeForMacro(outputFolder)).append("\";\n\n");
        sb.append("list = getFileList(inputDir);\n");
        sb.append("setBatchMode(true);\n\n");
        sb.append("for (i = 0; i < list.length; i++) {\n");
        sb.append("    if (endsWith(list[i], \".tif\") || endsWith(list[i], \".tiff\") || ");
        sb.append("endsWith(list[i], \".png\") || endsWith(list[i], \".jpg\")) {\n");
        sb.append("        open(inputDir + list[i]);\n\n");

        for (int s = 0; s < pipeline.steps.size(); s++) {
            PipelineStep step = pipeline.steps.get(s);
            sb.append("        // Step ").append(step.index).append(": ").append(step.description).append("\n");
            // Indent each line of the macro code
            String[] lines = step.macroCode.trim().split("\n");
            for (int l = 0; l < lines.length; l++) {
                sb.append("        ").append(lines[l].trim()).append("\n");
            }
            sb.append("\n");
        }

        sb.append("        // Save result\n");
        sb.append("        saveAs(\"Tiff\", outputDir + list[i]);\n");
        sb.append("        close();\n");
        sb.append("    }\n");
        sb.append("}\n\n");
        sb.append("setBatchMode(false);\n");
        sb.append("print(\"Batch processing complete: \" + list.length + \" files\");\n");
        return sb.toString();
    }

    // --- Private helpers ---

    /**
     * Execute pipeline steps starting from a given index.
     */
    private void executeFromStep(Pipeline pipeline, int startIndex, PipelineCallback callback) {
        for (int i = startIndex; i < pipeline.steps.size(); i++) {
            PipelineStep step = pipeline.steps.get(i);
            pipeline.currentStepIndex = i;

            step.status = "running";
            if (callback != null) {
                callback.onStepStarted(step);
            }

            long stepStart = System.currentTimeMillis();
            ExecutionResult result = commandEngine.executeMacro(step.macroCode);
            step.executionTimeMs = System.currentTimeMillis() - stepStart;
            step.result = result;

            if (result.isSuccess()) {
                step.status = "success";
                if (callback != null) {
                    callback.onStepCompleted(step);
                }
            } else {
                step.status = "failed";
                // Mark remaining steps as skipped
                for (int j = i + 1; j < pipeline.steps.size(); j++) {
                    pipeline.steps.get(j).status = "skipped";
                }
                pipeline.status = "failed";
                if (callback != null) {
                    callback.onStepFailed(step, result.getError());
                    callback.onPipelineFailed(pipeline, step);
                }
                return;
            }
        }

        pipeline.status = "completed";
        if (callback != null) {
            callback.onPipelineCompleted(pipeline);
        }
    }

    /**
     * Derive a pipeline name from the step descriptions.
     */
    private String derivePipelineName(List<PipelineStep> steps) {
        if (steps.isEmpty()) {
            return "Unnamed Pipeline";
        }
        // Use the last step's description as a hint for the pipeline purpose,
        // or combine first and last
        if (steps.size() == 1) {
            return steps.get(0).description;
        }
        String first = steps.get(0).description;
        String last = steps.get(steps.size() - 1).description;
        // Keep it short
        if (first.length() + last.length() > 60) {
            return first;
        }
        return first + " ... " + last;
    }

    /**
     * Escape backslashes for ImageJ macro string literals.
     */
    private String escapeForMacro(String path) {
        if (path == null) {
            return "";
        }
        return path.replace("\\", "/");
    }
}
