#!/usr/bin/env python
"""Generate the reference index deterministically with explicit input bounds."""

from __future__ import annotations

import argparse
import os
import re
import tempfile
from pathlib import Path


REFERENCE_DIR = Path(__file__).resolve().parent / "references"
INDEX_PATH = REFERENCE_DIR / "INDEX.md"
MAX_REFERENCE_FILES = 256
MAX_REFERENCE_BYTES = 512 * 1024
MAX_TOTAL_BYTES = 16 * 1024 * 1024
SUMMARY_LIMIT = 140


def _read_reference(path: Path) -> str:
    size = path.stat().st_size
    if size > MAX_REFERENCE_BYTES:
        raise ValueError(f"reference exceeds {MAX_REFERENCE_BYTES} byte limit: {path}")
    with path.open("rb") as handle:
        payload = handle.read(MAX_REFERENCE_BYTES + 1)
    if len(payload) > MAX_REFERENCE_BYTES:
        raise ValueError(f"reference exceeds {MAX_REFERENCE_BYTES} byte limit: {path}")
    return payload.decode("utf-8")


def _title_and_summary(filename: str, text: str) -> tuple[str, str]:
    lines = text.splitlines()
    title = filename[:-3].replace("-", " ").title()
    for line in lines:
        if line.startswith("# ") and line[2:].strip():
            title = line[2:].strip().replace("|", "\\|")
            break
    summary_parts = []
    in_fence = False
    for raw in lines:
        line = raw.strip()
        if line.startswith("```"):
            in_fence = not in_fence
            continue
        if (in_fence or not line or line.startswith("#") or line.startswith("|")
                or line.startswith("---") or line.startswith("<!--")):
            if summary_parts:
                break
            continue
        line = re.sub(r"^[*+-]\s+", "", line)
        summary_parts.append(line)
        if len(" ".join(summary_parts)) >= SUMMARY_LIMIT:
            break
    summary = re.sub(r"\s+", " ", " ".join(summary_parts)).strip()
    if len(summary) > SUMMARY_LIMIT:
        summary = summary[:SUMMARY_LIMIT - 1].rstrip() + "…"
    return title, (summary or "Reference notes.").replace("|", "\\|")


def render(reference_dir: Path = REFERENCE_DIR) -> str:
    paths = []
    with os.scandir(reference_dir) as entries:
        for entry in entries:
            if (entry.name.casefold() == "index.md"
                    or not entry.name.casefold().endswith(".md")
                    or not entry.is_file()):
                continue
            paths.append(Path(entry.path))
            if len(paths) > MAX_REFERENCE_FILES:
                raise ValueError(
                    f"reference count exceeds {MAX_REFERENCE_FILES} file limit"
                )
    paths.sort(key=lambda path: path.name.casefold())
    rows = []
    total_bytes = 0
    total_lines = 0
    for path in paths:
        text = _read_reference(path)
        total_bytes += len(text.encode("utf-8"))
        if total_bytes > MAX_TOTAL_BYTES:
            raise ValueError(
                f"reference inputs exceed {MAX_TOTAL_BYTES} total byte limit"
            )
        lines = len(text.splitlines())
        total_lines += lines
        title, summary = _title_and_summary(path.name, text)
        rows.append((path.name, title, lines, summary))

    output = [
        "# Reference Documents Index",
        "",
        "<!-- Auto-generated by agent/generate_reference_index.py. Do not edit by hand. -->",
        "",
        f"{len(rows)} reference documents, {total_lines:,} lines total.",
        "Read the relevant reference before starting an analysis in that domain.",
        "",
        "| Document | Title | Lines | Summary |",
        "|---|---|---:|---|",
    ]
    output.extend(
        f"| [{filename}]({filename}) | {title} | {lines} | {summary} |"
        for filename, title, lines, summary in rows
    )
    return "\n".join(output) + "\n"


def _atomic_write(path: Path, content: str) -> None:
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    except Exception:
        try:
            os.unlink(temporary)
        except OSError:
            pass
        raise


def generate(check: bool = False, reference_dir: Path = REFERENCE_DIR,
             index_path: Path = INDEX_PATH) -> bool:
    expected = render(reference_dir)
    current = None
    if index_path.exists() and index_path.stat().st_size <= MAX_REFERENCE_BYTES:
        current = _read_reference(index_path)
    changed = current != expected
    if changed and check:
        raise SystemExit(f"generated reference index is stale: {index_path}")
    if changed:
        _atomic_write(index_path, expected)
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail instead of rewriting a stale index")
    args = parser.parse_args()
    changed = generate(check=args.check)
    print("reference index is current" if args.check else
          ("updated reference index" if changed else "reference index unchanged"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
