"""Regenerate per-CLI-tool agent context files from the overlay loader.

Each CLI tool (Claude Code, Codex, Aider, Cline, Cursor, Gemini CLI)
auto-reads a fixed filename from the agent directory. This script
delegates to ``agent.contexts.loader.load_context(model_id)`` and
writes one composed file per CLI tool.

Phase F: replaces the legacy ``strip_claude_specific()`` regex with
composition driven by the unified ``agent/providers/models.yaml`` and
the overlays under ``agent/contexts/``. See
docs/multi_provider/04_context_strategy.md §5 for the migration plan.

Run after editing any overlay or the registry::

    python agent/sync_context.py
"""

from __future__ import annotations

import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
# Make `agent.contexts.loader` importable both when run directly
# (`python agent/sync_context.py`) and when imported as a module.
_PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)
if SCRIPT_DIR not in sys.path:
    sys.path.insert(0, SCRIPT_DIR)

try:  # package-relative import works when `agent` is on sys.path
    from agent.contexts import loader  # type: ignore[no-redef]
except ModuleNotFoundError:  # fall back to direct import via agent/contexts/
    sys.path.insert(0, os.path.join(SCRIPT_DIR, "contexts"))
    import loader  # type: ignore[no-redef]

# {output_filename (relative to agent/): provider/model_id consulted by the loader}
AGENT_FILES: dict[str, str] = {
    "CLAUDE.md": "anthropic/claude-opus-4-7",
    "AGENTS.md": "openai/gpt-5-codex",
    "GEMINI.md": "gemini/gemini-2.5-pro",
    ".aider.conventions.md": "anthropic/claude-sonnet-4-6",
    ".clinerules": "anthropic/claude-sonnet-4-6",
    ".cursorrules": "anthropic/claude-sonnet-4-6",
}

BANNER = (
    "<!-- Auto-generated by agent/contexts/loader.py via agent/sync_context.py.\n"
    "     Edit the source: agent/contexts/base.md, harness/, capabilities/,\n"
    "     reliability/, families/, or agent/providers/models.yaml. -->\n\n"
)


def sync() -> list[tuple[str, str]]:
    """Regenerate every CLI context file from the overlay loader."""
    generated: list[tuple[str, str]] = []
    for filename, model_id in AGENT_FILES.items():
        composed = loader.load_context(model_id)
        target = os.path.join(SCRIPT_DIR, filename)
        with open(target, "w", encoding="utf-8") as fh:
            fh.write(BANNER + composed)
        generated.append((filename, model_id))
        print("  [OK] {} <- loader.load_context({!r})".format(filename, model_id))
    return generated


def main() -> None:
    print("Regenerating agent CLI context files via the overlay loader...")
    print()
    results = sync()
    print()
    print("Wrote {} files.".format(len(results)))
    print(
        "These files are auto-generated. Edit base/harness/capabilities/"
        "reliability/family overlays and re-run this script to update."
    )


if __name__ == "__main__":
    main()
